#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server

if [ $# -lt 4 ]; then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
fi

path_2_file=$1
server_ip=$2
username=$3
ssh_key=$4

echo "Transferring file from $path_2_file to $username@$server_ip..."

# Adding -v for debugging SCP
scp -v -o StrictHostKeyChecking=no -i "$ssh_key" "$path_2_file" "$username"@"$server_ip":~/

if [ $? -eq 0 ]; then
    echo "File transferred successfully!"
else
    echo "File transfer failed."
fi

