#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to http://christechcoder.tech/ with a 301 response

# Update Nginx configuration file to include redirection
sed -i '/server {/a \
    location /redirect_me {\
        return 301 http://christechcoder.tech/;\
    }' /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
nginx -s reload

