#!/usr/bin/env bash
# This script updates /etc/hosts for localhost and facebook.com

# Change localhost to 127.0.0.2
sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts

# Change facebook.com to 8.8.8.8
sed -i '/facebook.com/c\8.8.8.8 facebook.com' /etc/hosts

