#!/usr/bin/env bash
# Configures localhost to resolve to 127.0.0.2 and facebook.com to resolve to 8.8.8.8

sudo sed -i 's/^127.0.0.1/127.0.0.2/' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

