#!/usr/bin/env bash
# This script creates an RSA key pair with the private key named 'school' and 4096 bits,
# protected by the passphrase 'betty'.

ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N "betty"

